var NoteConstants = {
  NOTES_RECEIVED: "NOTES_RECEIVED",
  NOTE_RECEIVED: "NOTE_RECEIVED",
  CREATE_NOTE: "CREATE_NOTE",
  EDIT_NOTE: "EDIT_NOTE",
  DELETE_NOTE: "DELETE_NOTE"
};

module.exports = NoteConstants;
